name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
    arduino-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: arduino/arduino-lint-action@v1.0.0
              with:
                  compliance: strict
                  project-type: sketch
                  recursive: true
